<div class="pdf-footer">
    <div>Generated by {{ config('app.name', 'Barangay Management System') }}</div>
    <div>Document released {{ $serviceRequest->released_at?->format('F d, Y h:i A') ?? '-' }}</div>
</div>
